#!/usr/bin/python3

import argparse
from datetime import datetime
import json
import logging
import os
import sys
import re
from zipfile import ZipFile, ZipInfo, ZIP_STORED

from misc.template import MANIFEST_MF, JAVACARD_XML, APPLET_XML

logger = logging.getLogger("JSON2CAP")
logger.setLevel(logging.INFO)

stream_handler = logging.StreamHandler()
logger_formatter = logging.Formatter(
    "%(asctime)s\t%(levelname)-5s\t%(message)s",
    # "%(asctime)s\t%(levelname)-5s\t%(filename)-21s: %(lineno)-3d\t%(funcName)-25s\t%(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
stream_handler.setFormatter(logger_formatter)
logger.addHandler(stream_handler)


# remove the comments, spaces, etc.
def clean_hex_string(input_str):
    # Remove content within (), i.e., comments
    input_str = re.sub(r"\(.*?\)", "", input_str)

    # Remove non-hex characters, i.e., separators (= keep only 0-9 and a-f/A-F)
    hex_only = re.sub(r"[^0-9a-fA-F]", "", input_str)

    return hex_only


class JSON2CAP:
    CONVERTION_TYPE_DEEP = "deep"  # based on the parsed elements in the JSON struct
    CONVERTION_TYPE_SHALLOW = (
        "shallow"  # based on raw elements (hex values) in the JSON struct
    )

    def __init__(self):
        pass

    def build_cap(
        self,
        json_cap,
        cap_file_name,
        conversion_mode=CONVERTION_TYPE_SHALLOW,
        packagename="helloworldPackage",
    ):
        if conversion_mode == self.CONVERTION_TYPE_SHALLOW:
            with ZipFile(cap_file_name, "w", ZIP_STORED) as cap_zip:
                for component_name in json_cap.keys():
                    info = ZipInfo(f"{packagename}/javacard/{component_name}")
                    info.compress_type = ZIP_STORED
                    info.create_system = (
                        0  # to be compatible with JCDK generated CAP files.
                    )
                    info.external_attr = (
                        0  # to be compatible with JCDK generated CAP files.
                    )
                    info.create_version = (
                        10  # to be compatible with JCDK generated CAP files.
                    )
                    component_data = bytes.fromhex(
                        clean_hex_string(
                            json_cap[component_name].get(
                                "raw_modified"
                            )  # due to "or", in case of having empty "raw_modified", the value of "raw_original" is used
                            or json_cap[component_name]["raw_original"]
                        )
                    )
                    cap_zip.writestr(info, component_data)
                    logger.debug(f"Added {component_name}")

                # Some installers may require the following files as well,
                # however, this is not the case for the tools that I worked
                # with. Hence, they are commented out by default. In case of
                # uncommenting, the contents shall ba checked to be valid for
                # the applet.

                # info = ZipInfo(f"META-INF/MANIFEST.MF")
                # info.compress_type = ZIP_STORED
                # info.create_system = 0
                # info.external_attr = 0
                # cap_zip.writestr(info, MANIFEST_MF)

                # info = ZipInfo(f"META-INF/javacard.xml")
                # info.compress_type = ZIP_STORED
                # info.create_system = 0
                # info.external_attr = 0
                # cap_zip.writestr(info, JAVACARD_XML)

                # info = ZipInfo(f"APPLET-INF/applet.xml")
                # info.compress_type = ZIP_STORED
                # info.create_system = 0
                # info.external_attr = 0
                # cap_zip.writestr(info, APPLET_XML)

            return True
        else:
            logger.error("Deep mode not implmeneted yet!")
            return False


def parse_arguments():
    parser = argparse.ArgumentParser(
        description="Read a JSON representaiton of a CAP file and generate corresponding CAP file."
    )
    parser.add_argument("json_path", help="Path to the input JSON file")
    parser.add_argument(
        "--output",
        "-o",
        help="Optional output file path and name (default: autogenerated with timestamp)",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing file if the provided output file name is not unique.",
    )
    parser.add_argument(
        "-m",
        "--mode",
        choices=["shallow", "deep"],
        default="shallow",
        help="Optional conversion mode: shallow mode (default) uses 'raw_modified' or 'raw' elements in JSON file, whereas deep mode uses parsed elements.",
    )

    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit(1)

    return parser.parse_args()


def main():
    args = parse_arguments()

    if not os.path.isfile(args.json_path):
        logger.error(f"File '{args.json_path}' does not exist.")
        sys.exit(1)

    if args.output:
        if os.path.exists(args.output) and not args.overwrite:
            logger.error(
                f"Output file '{args.output}' already exists. Use --overwrite or provide a new name."
            )
            sys.exit(1)
        output_file_name = args.output
    else:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        json_name = os.path.splitext(os.path.basename(args.json_path))[0]
        output_file_name = f"output{os.path.sep}{timestamp}_{json_name}_json.cap"

    try:
        input_file = open(args.json_path, "r", encoding="utf-8")
        json_cap = json.load(input_file)
        input_file.close()

        json2cap = JSON2CAP()
        if json2cap.build_cap(json_cap, output_file_name, args.mode):
            logger.info(f"Generated CAP file is available under '{output_file_name}'")
        else:
            logger.error("CAP File generation failed!")

    except Exception as e:
        print(f"An error occurred: {e}")


if __name__ == "__main__":
    main()
